export const GET_PRODUCTS_LOAD = "GET_PRODUCTS_LOAD";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCT_LOAD = "GET_PRODUCT_LOAD";
export const GET_PRODUCT = "GET_PRODUCT";

export const TOGGLE_TRUE = "TOGGLE_TRUE";

export const CREATE_REVIEW_LOAD = "CREATE_REVIEW_LOAD";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";

export const ADD_COMMENT = "ADD_COMMENT";

export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
export const GET_PRODUCT_SEARCH = "GET_PRODUCT_SEARCH";