export const UPLOAD_PHOTO = "UPLOAD_PHOTO";
export const UPLOAD_PHOTO_SUCCESS = "UPLOAD_PHOTO_SUCCESS";
export const UPLOAD_PHOTO_FAIL = "UPLOAD_PHOTO_FAIL";

export const DESTROY_PHOTO_SUCCESS = "DESTROY_PHOTO_SUCCESS";
export const DESTROY_PHOTO_FAIL = "DESTROY_PHOTO_FAIL";