export const PATIENT_LOGIN_REQUEST = 'PATIENT_LOGIN_REQUEST'
export const PATIENT_LOGIN_SUCCESS = 'PATIENT_LOGIN_SUCCESS'
export const PATIENT_LOGIN_FAIL = 'PATIENT_LOGIN_FAIL'


export const PATIENT_REGISTER_REQUEST = 'PATIENT_REGISTER_REQUEST'
export const PATIENT_REGISTER_SUCCESS = 'PATIENT_REGISTER_SUCCESS'
export const PATIENT_REGISTER_FAIL = 'PATIENT_REGISTER_FAIL'

export const PATIENT_LOGOUT_REQUEST = 'PATIENT_LOGOUT_REQUEST'
export const PATIENT_LOGOUT_SUCCESS = 'PATIENT_LOGOUT_SUCCESS'
export const PATIENT_LOGOUT_FAIL = 'PATIENT_LOGOUT_FAIL'

//Atelier

export const ATELIER_LOGIN_REQUEST = 'ATELIER_LOGIN_REQUEST'
export const ATELIER_LOGIN_SUCCESS = 'ATELIER_LOGIN_SUCCESS'
export const ATELIER_LOGIN_FAIL = 'ATELIER_LOGIN_FAIL'


export const ATELIER_REGISTER_REQUEST = 'ATELIER_REGISTER_REQUEST'
export const ATELIER_REGISTER_SUCCESS = 'ATELIER_REGISTER_SUCCESS'
export const ATELIER_REGISTER_FAIL = 'ATELIER_REGISTER_FAIL'

export const ATELIER_LOGOUT_REQUEST = 'ATELIER_LOGOUT_REQUEST'
export const ATELIER_LOGOUT_SUCCESS = 'ATELIER_LOGOUT_SUCCESS'
export const ATELIER_LOGOUT_FAIL = 'ATELIER_LOGOUT_FAIL'

//Admin

export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'

export const ADMIN_LOGOUT_REQUEST = 'ADMIN_LOGOUT_REQUEST'
export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS'
export const ADMIN_LOGOUT_FAIL = 'ADMIN_LOGOUT_FAIL'

//PROFILE_UPDATE_FAIL
export const GET_USER = 'GET_USER'
export const GET_USER_FAIL = 'GET_USER_FAIL'
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS'
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL'
